#!/bin/sh

# Set these paths appropriately

BIN=/ai/home/esert/semeval-2013/bin/tree-tagger/bin
CMD=/ai/home/esert/semeval-2013/bin/tree-tagger/cmd
LIB=/ai/home/esert/semeval-2013/bin/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/estonian-abbreviations
PARFILE=${LIB}/estonian.par
MWLFILE=${LIB}/estonian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

