#!/bin/sh

# Set these paths appropriately

BIN=/ai/home/esert/semeval-2013/bin/tree-tagger/bin
CMD=/ai/home/esert/semeval-2013/bin/tree-tagger/cmd
LIB=/ai/home/esert/semeval-2013/bin/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/french-abbreviations
PARFILE=${LIB}/french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
