#!/bin/sh

# Set these paths appropriately

BIN=/ai/home/esert/semeval-2013/bin/tree-tagger/bin
CMD=/ai/home/esert/semeval-2013/bin/tree-tagger/cmd
LIB=/ai/home/esert/semeval-2013/bin/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

