#!/bin/sh

# Set these paths appropriately

BIN=/ai/home/esert/semeval-2013/bin/tree-tagger/bin
CMD=/ai/home/esert/semeval-2013/bin/tree-tagger/cmd
LIB=/ai/home/esert/semeval-2013/bin/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/bulgarian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
